#
# set +o errexit -o noglob -o nounset is assumed.
#

pkg_install_subdirs() {
	local _spec="";
	for _spec in \
			"${PKG_INSTALL_FILES_DESTDIR:-}"	\
			"${PKG_INSTALL_FILES_DESTDIR_EXTRA:-}"; do
		if ! rtl_install "${PKG_DESTDIR}" ${_spec}; then
			return 1;
		fi;
	done;
	if [ "${PKG_PREFIX%/}" = "${PREFIX_NATIVE%/}" ]; then
		if ! rtl_install "${PKG_DESTDIR}/${DEFAULT_TARGET}" ${PKG_INSTALL_FILES_DESTDIR}; then
			return 1;
		fi;
	fi;
};

# vim:filetype=sh
