#
# set -o errexit -o noglob are assumed.
#

pkg_configure_patch_pre() {
	local _patch_path;
	for _patch_path in 											\
			${MIDIPIX_BUILD_PWD}/patches/${PKG_NAME}${PKG_VERSION:+-${PKG_VERSION}}_pre.local.patch	\
			${MIDIPIX_BUILD_PWD}/patches/${PKG_NAME}${PKG_VERSION:+-${PKG_VERSION}}_pre.local@${BUILD_HNAME}.patch; do
		if [ -r "${_patch_path}" ]; then
			patch -b -d "${PKG_BASE_DIR}/${PKG_SUBDIR}" -p1 < "${_patch_path}";
		fi;
	done;
};

# vim:filetype=sh
