#
# set -o errexit -o noglob are assumed.
#

pkg_build_dir() {
	if [ -z "${PKG_BUILD_DIR}" ]; then
		if [ -e "${PKG_BASE_DIR}/${PKG_SUBDIR}/configure" ]\
		|| [ -e "${PKG_BASE_DIR}/${PKG_SUBDIR}/configure.ac" ]\
		|| [ -e "${PKG_BASE_DIR}/${PKG_SUBDIR}/configure.in" ]; then
			PKG_BUILD_DIR="${PKG_BASE_DIR}/obj";
		else
			PKG_BUILD_DIR="${PKG_BASE_DIR}/${PKG_SUBDIR}";
		fi;
	else
		PKG_BUILD_DIR="${PKG_BASE_DIR}/${PKG_BUILD_DIR}";
	fi;
};

# vim:filetype=sh
