#
# set +o errexit -o noglob is assumed.
#

pkg_clean() {
	if [ "${PKG_NO_CLEAN:-0}" -eq 0 ]; then
		if rtl_lmatch "${ARG_CLEAN_BUILDS}" "build" ","; then
			rtl_fileop rm "${PKG_BUILD_DIR}" || return "${?}";
		fi;
		if rtl_lmatch "${ARG_CLEAN_BUILDS}" "dest" ","; then
			rtl_fileop rm "${PKG_DESTDIR}" || return "${?}";
		fi;
		if rtl_lmatch "${ARG_CLEAN_BUILDS}" "src" ","; then
			rtl_fileop rm "${PKG_BASE_DIR}/${PKG_SUBDIR}" || return "${?}";
		fi;
	fi;
};

# vim:filetype=sh
