#
# set -o errexit -o noglob are assumed.
#

pkg_clean() {
	local _dir="";
	if [ -n "${PKG_DEPS_BASE}" ]; then
		return 0;
	fi;
	if ex_rtl_lmatch "${ARG_CLEAN_BUILDS}" , build; then
		ex_rtl_fileop rm "${PKG_BUILD_DIR}";
	fi;
	if ex_rtl_lmatch "${ARG_CLEAN_BUILDS}" , dest; then
		ex_rtl_fileop rm "${PKG_DESTDIR}";
	fi;
	if ex_rtl_lmatch "${ARG_CLEAN_BUILDS}" , src; then
		ex_rtl_fileop rm "${PKG_BASE_DIR}/${PKG_SUBDIR}";
	fi;
};

# vim:filetype=sh
