#
# set -o errexit -o noglob are assumed.
#

post_strip() {
	local __;
	if [ ${BUILD_SCRIPT_RC:-0} -eq 0 ]\
	&& [ "${BUILD}" = release ]; then
		for __ in $(find ${PREFIX_NATIVE}/bin -perm -0100 \( -type f -or -type l \)); do
			if objdump -sj .debug_info >/dev/null 2>&1; then
				log_msg vnfo "${PKG_TARGET}-strip ${__}";
				set +o errexit; ${PKG_TARGET}-strip ${__}; set -o errexit;
			fi;
		done;
	fi;
};

# vim:filetype=sh
