#
# set -o errexit -o noglob are assumed.
#

post_build_files() {
	: $((BUILD_TIMES_SECS=$(command date +%s)-${BUILD_TIMES_SECS}));
	: $((BUILD_TIMES_HOURS=${BUILD_TIMES_SECS}/3600));
	: $((BUILD_TIMES_MINUTES=(${BUILD_TIMES_SECS}%3600)/60));
	: $((BUILD_TIMES_SECS=(${BUILD_TIMES_SECS}%3600)%60));
	if [ -f "${BUILD_STATUS_IN_PROGRESS_FNAME}" ]; then
		build_fileop rm ${BUILD_STATUS_IN_PROGRESS_FNAME};
	fi;
};

# vim:filetype=sh
